apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensebox-metrics-exporter
  labels:
    app: sensebox
  namespace: food-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensebox
  template:
    metadata:
      labels:
        app: sensebox
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: sensebox-metrics-exporter
          image: ghcr.io/sijoma/sensebox-metrics-exporter
          ports:
            - containerPort: 9500
              name: metricz
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"


